"""is_active column added

Revision ID: 06e352647cb9
Revises: 1a85c6eaf99f
Create Date: 2024-10-22 14:06:54.635447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e352647cb9'
down_revision: Union[str, None] = '1a85c6eaf99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_public_users_email', table_name='users')
    op.drop_index('ix_public_users_id', table_name='users')
    op.drop_index('ix_public_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_public_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_public_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_public_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
